### ISSUE TITLE
Unexpected behavior during single recursion on Windows

### ISSUE THREAD

**Issue by ldesgoui** [peace-maker/DHooks2#3]
Hello,

I've been having an issue with one of my detours, it consists of overriding the return of a recursive call, I have a small writeup about it: https://github.com/ldesgoui/tf2-comp-fixes/blob/master/INTERNALS.md#remove-medic-attach-speed

On Linux, simply hooking the pre, setting the return if the boolean argument is true (and therefore we're recursing), and returing Override/Supercede works fine.
On Windows, it seems that overriding the recursed call will cause the "host" call to also return the same value, I'm sure of this because code later in the function is completely ignored (such as the code to handle Mannpower mode powerups, can be verified by running `addcond 91`).
Assuming I haven't done anything blatantly wrong, how could I help you fix the issue? How could I circumvent it for the time being?

My hook definition is as such: https://github.com/ldesgoui/tf2-comp-fixes/blob/4119ed81273edbb50f7026e4614a2bbc7115be62/gamedata/tf2-comp-fixes.games.txt#L95-L106

If you'd like to read the disassembly of the method in question, it's in TF2's tf/bin/server.dll, it contains the unique string `mult_player_aiming_movespeed`. I'm not exactly fluent, but I haven't found anything blatantly wrong with it.

Thank you

**Comment by peace-maker** [comment]
Looks like this issue was fixed in DynamicHooks just recently!
https://github.com/Ayuto/DynamicHooks/pull/4

**Comment by peace-maker** [comment]
I'm not sure how this would explain the behavior you're describing, but I'm not complaining.
At a quick glance recursion isn't supported yet, since the saved register values of the hook will be overwritten by the recursive call. so when returning from the parent call eventually it'll restore the register values of the recursive call.

You're welcome to try this build with the above fix included and see if that already helps :)

[dhooks.ext.zip](https://github.com/peace-maker/DHooks2/files/4629831/dhooks.ext.zip)

**Comment by ldesgoui** [comment]
Unfortunately, from the limited testing I can do right now, it does not appear to fix the issue.

**Comment by jordanbriere** [comment]
I don't think this is related to https://github.com/Ayuto/DynamicHooks/pull/4. If it was, the server would just freeze as the post handler would call itself infinitely.

Based on the behaviours described, and seeing that this function returns a float, my first guess would be [hook.cpp#L406](https://github.com/peace-maker/DHooks2/blob/dynhooks/DynamicHooks/hook.cpp#L406) and [hook.cpp#L471](https://github.com/peace-maker/DHooks2/blob/dynhooks/DynamicHooks/hook.cpp#L471) causing the first call to restore the inner's st0 because it wasn't saved in pre but possibly re-used by the recursive call.

I believe you added those conditions to fix issues related to https://github.com/Ayuto/DynamicHooks/pull/3.

**Comment by peace-maker** [comment]
But the return value isn't in st0 during a pre-hook yet, so there is nothing to be saved?

I think this particular bug is `m_LastPreReturnAction` being overwritten by the recursive call and used in the parent call as well. https://github.com/peace-maker/DHooks2/blob/dynhooks/DynamicHooks/hook.cpp#L181

It's not in the original DynamicHooks library. It's here to mimic the hooking possibilities in SourceHook in a pre hook. `Override`: run the original function, but return my changed return value, `Supercede`: don't run the original function and just return my changed return value.
https://github.com/peace-maker/DHooks2/commit/1a2040e00b6c4c4f3cb9f727166b0bc302955a67

The saved `this` and return value from the pre hook gets overwritten by the recursive call as well. So I guess we need a stack for all those values as well.

**Comment by peace-maker** [comment]
Here's another build with the above fix included.
[dhooks.ext.zip](https://github.com/peace-maker/DHooks2/files/4633848/dhooks.ext.zip)

**Comment by ldesgoui** [comment]
It has solved the issue, thank you very much.

**Comment by peace-maker** [comment]
I don't understand why it was only a problem on windows for you and not on linux, but I don't have time to check out the actual assembly of the function.

**Comment by ldesgoui** [comment]
Could you please publish a new release with this? Thank you.
On another note, it appears that this bug also affects some Linux installations (that I don't have access to so I can't tell you what would be different).

**Comment by peace-maker** [comment]
Yup, did it now.
